name: Bug
description: Bug report
labels: ["bug"]
body:
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
